### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [frodestorhaug/GTM-AjaxRequestListener#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) The documentation [url](https://github.com/frodestorhaug/GTM-AjaxRequestListener/README.md) provided in the metadata file shows "Page not found" error. Please provide valid url
![Screenshot 2021-03-18 2 24 42 PM](https://user-images.githubusercontent.com/53495700/111700060-20631100-87f6-11eb-8d5a-fedefec96b3b.png)

**Comment by frodestorhaug** [comment]
Thanks for your feedback, the url is updated
